# Generated by Django 6.0.5 on 2026-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('can_judge_photos', 'Can explicitly access judging panels and submit grades')]},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
