# Generated by Django 6.0.5 on 2026-05-24 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0002_alter_photo_options_alter_photo_photographer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='score',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='max_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='judging_app.photo'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='photo',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='judging_app.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging_app.competition'),
            preserve_default=False,
        ),
    ]
