# Generated by Django 6.0.5 on 2026-05-25 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0003_competition_remove_score_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judged_competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
