# Generated by Django 6.0.5 on 2026-05-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0004_competition_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tie_breaker_criterion',
            field=models.ForeignKey(blank=True, help_text='If two photos have the same average total score, the higher average score in this specific category wins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_breaker_for', to='judging_app.rubriccriterion'),
        ),
    ]
