# Generated by Django 6.0.5 on 2026-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0005_competition_tie_breaker_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='organizer_notes',
            field=models.TextField(blank=True, help_text="Organizer's final feedback or notes for this photo."),
        ),
    ]
