# Generated by Django 6.0.5 on 2026-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0006_photo_organizer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='rule_flags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
