# Generated by Django 6.0.5 on 2026-05-26 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0008_photo_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='rubriccriterion',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='score',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, help_text="Clean URL text (e.g., 'youth-poty' or 'shutter-society')", max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_breaker_for', to='judging_app.rubriccriterion'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging_app.competition'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='competition_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='organizer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='judging_app.competition'),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging_app.photo'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
