# Generated by Django 6.0.5 on 2026-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0009_alter_photo_options_remove_competition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera_settings',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
