# Generated by Django 6.0.5 on 2026-05-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0011_zipimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipimportjob',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
