# Generated by Django 6.0.5 on 2026-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0012_zipimportjob_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_settings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to='competition_photos/'),
        ),
        migrations.AlterField(
            model_name='zipimportjob',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='zipimportjob',
            name='temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
