# Generated by Django 6.0.5 on 2026-05-26 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0014_photo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStatusVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('SHORTLIST', 'Shortlist'), ('REJECT', 'Reject')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_votes', to='judging_app.photo')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_status_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('photo', 'voter')},
            },
        ),
    ]
