# Generated by Django 6.0.5 on 2026-05-26 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_existing_triage_votes_to_round_1(apps, schema_editor):
    Photo = apps.get_model('judging_app', 'Photo')
    PhotoStatusVote = apps.get_model('judging_app', 'PhotoStatusVote')
    Photo.objects.filter(status='SHORTLISTED').update(status='ROUND_1')
    PhotoStatusVote.objects.filter(decision='SHORTLIST').update(decision='ROUND_1')


def move_round_1_votes_back_to_shortlist(apps, schema_editor):
    Photo = apps.get_model('judging_app', 'Photo')
    PhotoStatusVote = apps.get_model('judging_app', 'PhotoStatusVote')
    Photo.objects.filter(status='ROUND_1').update(status='SHORTLISTED')
    PhotoStatusVote.objects.filter(decision='ROUND_1').update(decision='SHORTLIST')


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0015_photostatusvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            move_existing_triage_votes_to_round_1,
            move_round_1_votes_back_to_shortlist,
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ROUND_1', 'Round 1'), ('SHORTLISTED', 'Shortlisted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='photostatusvote',
            name='decision',
            field=models.CharField(choices=[('ROUND_1', 'Advance to Round 1'), ('REJECT', 'Reject')], max_length=20),
        ),
        migrations.CreateModel(
            name='GutCheckScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gut_check_scores', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gut_check_scores', to='judging_app.photo')),
            ],
            options={
                'unique_together': {('photo', 'judge')},
            },
        ),
    ]
