# Generated by Django 6.0.5 on 2026-05-26 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0016_alter_photo_status_alter_photostatusvote_decision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GutCheckScore',
            new_name='RoundOneScore',
        ),
        migrations.AlterField(
            model_name='roundonescore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_1_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roundonescore',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_1_scores', to='judging_app.photo'),
        ),
        migrations.AlterField(
            model_name='roundonescore',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
