# Generated by Django 6.0.5 on 2026-05-26 21:18

import judging_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0017_rename_gutcheckscore_roundonescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to=judging_app.models.competition_photo_upload_path),
        ),
    ]
