# Generated by Django 6.0.5 on 2026-05-27 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_competition_memberships(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Competition = apps.get_model('judging_app', 'Competition')
    CompetitionMembership = apps.get_model('judging_app', 'CompetitionMembership')

    competitions = list(Competition.objects.all())

    if not User.objects.filter(is_superuser=True).exists():
        first_staff = User.objects.filter(is_staff=True, is_active=True).order_by('id').first()
        if first_staff:
            first_staff.is_superuser = True
            first_staff.is_staff = True
            first_staff.save(update_fields=['is_superuser', 'is_staff'])

    old_staff_users = list(User.objects.filter(is_staff=True, is_superuser=False, is_active=True))
    for competition in competitions:
        for user in old_staff_users:
            CompetitionMembership.objects.get_or_create(
                competition=competition,
                user=user,
                role='ORGANIZER',
                defaults={'is_active': True},
            )

        for user in competition.judges.all():
            CompetitionMembership.objects.get_or_create(
                competition=competition,
                user=user,
                role='VIP_JUDGE',
                defaults={'is_active': True},
            )

    User.objects.filter(is_staff=True, is_superuser=False).update(is_staff=False)


def reverse_seed_competition_memberships(apps, schema_editor):
    CompetitionMembership = apps.get_model('judging_app', 'CompetitionMembership')
    CompetitionMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0018_alter_photo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZER', 'Competition Organizer'), ('INTERNAL_JUDGE', 'Internal Reviewer'), ('VIP_JUDGE', 'VIP Guest Judge')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='judging_app.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competition__name', 'user__username', 'role'],
                'unique_together': {('competition', 'user', 'role')},
            },
        ),
        migrations.RunPython(seed_competition_memberships, reverse_seed_competition_memberships),
    ]
