# Generated by Django 6.0.5 on 2026-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0019_competitionmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='workflow',
            field=models.CharField(choices=[('FULL_COMPETITION', 'Full competition funnel'), ('FEEDBACK_PORTAL', 'Feedback portal')], default='FULL_COMPETITION', max_length=30),
        ),
    ]
