# Generated by Django 6.0.5 on 2026-06-01 06:56

from django.db import migrations, models


def backfill_entry_codes(apps, schema_editor):
    Photo = apps.get_model('judging_app', 'Photo')
    for photo in Photo.objects.filter(entry_code=''):
        photo.entry_code = str(photo.id)
        photo.save(update_fields=['entry_code'])


def clear_backfilled_entry_codes(apps, schema_editor):
    Photo = apps.get_model('judging_app', 'Photo')
    Photo.objects.update(entry_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0020_competition_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='entry_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_entry_codes, clear_backfilled_entry_codes),
    ]
