# Generated by Django 6.0.5 on 2026-06-01 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0021_photo_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriterion',
            name='score_out_of',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
