# Generated by Django 6.0.5 on 2026-06-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0024_competition_entry_fee_entryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmembership',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Competition Organizer'), ('INTERNAL_JUDGE', 'Internal Reviewer'), ('VIP_JUDGE', 'VIP Guest Judge'), ('ENTRANT', 'Entrant')], max_length=30),
        ),
    ]
