# Generated by Django 6.0.5 on 2026-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0025_alter_competitionmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='emails_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
    ]
