# Generated by Django 6.0.5 on 2026-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0026_competition_emails_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
