# Generated by Django 6.0.5 on 2026-06-02 07:59

import judging_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0027_photo_photographer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_warning_flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_raw_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='raw_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=judging_app.models.competition_raw_upload_path),
        ),
    ]
