# Generated by Django 6.0.5 on 2026-09-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0029_competition_judge_invite_token_and_related_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeProgressNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('TRIAGE', 'Triage review'), ('ROUND_1', 'Round 1 scoring'), ('FINAL', 'Final judging')], max_length=20)),
                ('milestone', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_progress_notifications', to='judging_app.competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_progress_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'judge', 'stage', 'milestone'), name='unique_judge_progress_notification')],
            },
        ),
    ]
