# Generated by Django 6.0.5 on 2026-09-29

import re

import django.db.models.deletion
from django.db import migrations, models


def create_shutter_society_series(apps, schema_editor):
    Competition = apps.get_model('judging_app', 'Competition')
    CompetitionSeries = apps.get_model('judging_app', 'CompetitionSeries')

    matching_competitions = []
    for competition in Competition.objects.all():
        identity = re.sub(r'[^a-z0-9]+', '', f'{competition.name} {competition.slug or ""}'.lower())
        if 'shuttersociety' in identity:
            matching_competitions.append(competition)

    if not matching_competitions:
        return

    series, _created = CompetitionSeries.objects.get_or_create(
        slug='shutter-society',
        defaults={'name': 'Shutter Society', 'is_active': True},
    )
    for index, competition in enumerate(sorted(matching_competitions, key=lambda item: (item.created_at, item.id)), start=1):
        remainder = re.sub(
            r'^shutter\s*society\s*[-:|]?\s*',
            '',
            competition.name,
            flags=re.IGNORECASE,
        ).strip()
        competition.series_id = series.id
        competition.edition_name = remainder or ('Original edition' if index == 1 else f'Edition {index}')
        competition.save(update_fields=['series', 'edition_name'])


def remove_shutter_society_series(apps, schema_editor):
    Competition = apps.get_model('judging_app', 'Competition')
    CompetitionSeries = apps.get_model('judging_app', 'CompetitionSeries')
    series = CompetitionSeries.objects.filter(slug='shutter-society').first()
    if not series:
        return
    Competition.objects.filter(series_id=series.id).update(series=None, edition_name='')
    series.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('judging_app', '0030_judgeprogressnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'competition series',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='edition_name',
            field=models.CharField(blank=True, help_text="Edition label within a series (for example, 'October 2026').", max_length=120),
        ),
        migrations.AddField(
            model_name='competition',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='judging_app.competitionseries'),
        ),
        migrations.RunPython(create_shutter_society_series, remove_shutter_society_series),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('series', 'edition_name'), name='unique_series_edition_name'),
        ),
    ]
